services:
  backend:
    image: arinkkk/dagaga-backend:latest
    container_name: dagaga-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/.env
    networks:
      - app-network
  frontend:
    image: arinkkk/dagaga-frontend:latest
    container_name: dagaga-frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge