services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dagaga-backend
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
