FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_api.txt .
RUN pip install --no-cache-dir -r requirements_api.txt

COPY api.py .
COPY .env .

# Expose port
EXPOSE 4000

# Run application
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "4000"]
